kind: pipeline
type: docker
name: default

trigger:
  branch:
  - sg

steps:
- name: build
  image: %%{GolangDevImage}:1-alpine
  pull: always
  settings:
    build_script: build.sh

- name: scan
  image: %%{NcicdDockerRepoPrivateCR}/cicd/nancy:latest
  pull: always
  failure: ignore
  depends_on:
  - build

- name: create-image
  image: %%{DroneDockerImage}
  settings:
    repo: %%{NcicdDockerRepo}/cicd/drone-server
    dockerfile: Dockerfile.sg
    build_args:
    - BASE_IMAGE=%%{BaseAlpineImage}:latest
    tags:
    - 20220621
  depends_on:
  - scan
  when:
    event:
    - promote

