kind: pipeline
type: docker
name: default

trigger:
  branch:
  - test

steps:
- name: build
  image: %%{GolangDevImage}:1-alpine
  pull: always
  settings:
    build_script: build.sh

- name: scan
  image: %%{NcicdDockerRepo}/cicd/nancy:latest
  pull: always
  failure: ignore
  depends_on:
  - build

