ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN if [ ! -e /etc/nsswitch.conf ]; then echo 'hosts: files dns' > /etc/nsswitch.conf; fi
ENV GODEBUG="netdns=go" \
    XDG_CACHE_HOME=/data \
    DRONE_DATABASE_DRIVER=sqlite3 \
    DRONE_DATABASE_DATASOURCE=/data/database.sqlite \
    DRONE_RUNNER_OS=linux \
    DRONE_RUNNER_ARCH=amd64 \
    DRONE_SERVER_PORT=:80 \
    DRONE_SERVER_HOST=localhost \
    DRONE_CONVERT_MULTI=true
COPY ./drone-server /bin/drone-server
ENTRYPOINT ["/bin/drone-server"]

